'use strict';
const $ = id => document.getElementById(id);
// Biblioteca 1: Darkmode.js. A biblioteca controla a transformação visual.
let darkmode;
try { darkmode = new Darkmode({ time: '0s', saveInCookies: false, autoMatchOsTheme: false }); }
catch { $('theme').disabled = true; $('theme').title = 'Modo escuro indisponível'; }
$('theme').addEventListener('click', () => { darkmode.toggle(); const active = darkmode.isActivated(); $('theme').setAttribute('aria-pressed', String(active)); $('theme').querySelector('span').textContent = active ? 'Modo claro' : 'Modo escuro'; });
// Biblioteca 2: Alertify.js. O feedback também permanece em uma região viva.
if (window.alertify) { alertify.defaults.glossary.ok = 'Entendi'; alertify.defaults.glossary.cancel = 'Cancelar'; alertify.defaults.transition = 'fade'; }
function notify(title, text) { if (window.alertify) alertify.alert(title, text); }
const questions = [
 { text: 'O voto em branco vai para quem está ganhando?', options: ['Sim, vai para o candidato mais votado.', 'Não. Ele não é atribuído a nenhum candidato.', 'Sim, é dividido entre os partidos.'], correct: 1, explanation: 'O voto em branco não é transferido para candidatos ou partidos. Ele fica fora da contagem dos votos válidos.' },
 { text: 'Qual destas opções é um voto válido?', options: ['Um voto em branco.', 'Um voto nulo.', 'Um voto atribuído a uma candidatura.'], correct: 2, explanation: 'Votos atribuídos a candidaturas são válidos. Nas eleições proporcionais, o voto de legenda também é válido. Brancos e nulos ficam fora desse cálculo.' },
 { text: 'A maioria de votos nulos escolhidos pelos eleitores cancela a eleição?', options: ['Não. Esses votos não cancelam a eleição.', 'Sim, a eleição sempre é repetida.', 'Sim, se houver votos em branco também.'], correct: 0, explanation: 'Votos brancos e nulos por opção dos eleitores não cancelam a eleição, mesmo em maioria. Isso é diferente da anulação judicial por irregularidades.' }
];
let qi = 0, score = 0, answered = false;
function renderQuestion() { answered = false; const q = questions[qi]; $('qcount').textContent = `QUESTÃO ${String(qi + 1).padStart(2, '0')} / 03`; $('score').textContent = `${score} ${score === 1 ? 'acerto' : 'acertos'}`; $('progress').value = qi; $('question').textContent = q.text; $('answers').replaceChildren(); q.options.forEach((text, index) => { const label = document.createElement('label'); label.className = 'option'; const input = document.createElement('input'); input.type = 'radio'; input.name = 'answer'; input.value = String(index); const span = document.createElement('span'); span.textContent = text; label.append(input, span); $('answers').append(label); }); $('feedback').textContent = ''; $('check').hidden = false; $('next').hidden = true; $('restart').hidden = true; }
$('quiz-form').addEventListener('submit', e => { e.preventDefault(); if (answered) return; const choice = document.querySelector('input[name="answer"]:checked'); if (!choice) { $('feedback').textContent = 'Escolha uma resposta antes de conferir.'; notify('Falta uma resposta', $('feedback').textContent); return; } answered = true; const correct = Number(choice.value) === questions[qi].correct; if (correct) score++; const title = correct ? 'Resposta correta!' : 'Vamos entender melhor'; $('feedback').textContent = `${title} ${questions[qi].explanation}`; $('score').textContent = `${score} ${score === 1 ? 'acerto' : 'acertos'}`; $('progress').value = qi + 1; document.querySelectorAll('input[name="answer"]').forEach(input => input.disabled = true); $('check').hidden = true; if (qi < 2) { $('next').hidden = false; $('next').focus(); } else { $('restart').hidden = false; $('restart').focus(); $('qcount').textContent = 'QUIZ CONCLUÍDO'; $('feedback').textContent += ` Você acertou ${score} de 3 perguntas.`; } notify(title, questions[qi].explanation); });
$('next').addEventListener('click', () => { qi++; renderQuestion(); document.querySelector('input[name="answer"]').focus(); });
$('restart').addEventListener('click', () => { qi = 0; score = 0; renderQuestion(); document.querySelector('input[name="answer"]').focus(); });
renderQuestion();
// Biblioteca 3: RecordRTC. getUserMedia solicita permissão; nenhum áudio é enviado.
let recorder, stream, interval, blobUrl, seconds = 0, recording = false, pending = false;
function releaseMicrophone() { if (stream) stream.getTracks().forEach(track => track.stop()); stream = null; clearInterval(interval); }
function clearAudio() { $('audio').pause(); $('audio').removeAttribute('src'); $('audio').load(); if (blobUrl) URL.revokeObjectURL(blobUrl); blobUrl = null; $('download').removeAttribute('href'); $('playback').hidden = true; }
function recorderError(error) { recording = false; pending = false; releaseMicrophone(); $('record').disabled = false; $('stop').disabled = true; const msg = error?.name === 'NotAllowedError' ? 'Permissão negada. Autorize o microfone nas configurações do navegador para gravar.' : error?.name === 'NotFoundError' ? 'Nenhum microfone foi encontrado. Conecte um microfone e tente novamente.' : 'Não foi possível gravar. Verifique o microfone e tente em um navegador compatível, usando HTTPS ou localhost.'; $('record-status').textContent = msg; notify('Gravação indisponível', msg); }
async function startRecording() { if (recording || pending) return; if (!navigator.mediaDevices?.getUserMedia || !window.RecordRTC) { recorderError(); return; } pending = true; $('record').disabled = true; $('record-status').textContent = 'Aguardando permissão do microfone…'; try { stream = await navigator.mediaDevices.getUserMedia({ audio: true }); if (recorder) recorder.destroy(); clearAudio(); recorder = RecordRTC(stream, { type: 'audio', disableLogs: true }); recorder.startRecording(); pending = false; recording = true; seconds = 0; $('timer').textContent = '00:00'; $('record-status').textContent = 'Gravando. Fale sua anotação.'; $('stop').disabled = false; $('stop').focus(); interval = setInterval(() => { seconds++; $('timer').textContent = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; if (seconds >= 120) stopRecording(); }, 1000); } catch (error) { recorderError(error); } }
function stopRecording() { if (!recording) return; recording = false; clearInterval(interval); $('stop').disabled = true; $('record-status').textContent = 'Preparando seu áudio…'; try { recorder.stopRecording(() => { try { const blob = recorder.getBlob(); releaseMicrophone(); if (!blob || blob.size === 0) throw new Error('Empty recording'); blobUrl = URL.createObjectURL(blob); $('audio').src = blobUrl; $('download').href = blobUrl; const ext = blob.type.includes('wav') ? 'wav' : blob.type.includes('ogg') ? 'ogg' : blob.type.includes('mp4') ? 'm4a' : 'webm'; $('download').download = `minha-anotacao-eleicoes.${ext}`; $('playback').hidden = false; $('record').disabled = false; $('record').textContent = 'Gravar novamente'; $('record-status').textContent = 'Áudio pronto. Ouça ou baixe sua anotação.'; $('download').focus(); } catch (error) { recorderError(error); } }); } catch (error) { recorderError(error); } }
$('record').addEventListener('click', startRecording); $('stop').addEventListener('click', stopRecording); $('discard').addEventListener('click', () => { clearAudio(); $('record-status').textContent = 'Gravação excluída. Pronto para gravar.'; $('record').textContent = 'Gravar áudio'; $('timer').textContent = '00:00'; $('record').focus(); });
window.addEventListener('pagehide', () => { releaseMicrophone(); if (blobUrl) URL.revokeObjectURL(blobUrl); });
const slides = [
 ['Eleições, cidadania e acessibilidade', '<p>Voto em Foco · Programação Web I</p><p>Uma página educativa, apartidária, com três bibliotecas JavaScript de funcionalidades diferentes.</p><p>Objetivo: aprender sobre o voto e demonstrar como códigos prontos acrescentam recursos a uma página HTML.</p>'],
 ['Como a página foi construída', '<ul><li>HTML organiza o conteúdo, os formulários e os botões.</li><li>CSS define o visual e adapta a página ao celular.</li><li>JavaScript conecta as ações às três bibliotecas.</li></ul><p>Os arquivos das bibliotecas são carregados antes de app.js, usando defer. As cópias locais evitam depender de uma CDN durante a apresentação.</p><pre>&lt;script defer src="vendor/darkmode.js"&gt;&lt;/script&gt;\n&lt;script defer src="app.js"&gt;&lt;/script&gt;</pre>'],
 ['01 · Darkmode.js', '<p><strong>Para que serve:</strong> alternar a aparência da página entre claro e escuro.</p><p><strong>Como usamos:</strong> o botão do cabeçalho chama toggle(). isActivated() atualiza o texto e o estado acessível do botão.</p><pre>const darkmode = new Darkmode({\n  autoMatchOsTheme: false\n});\ndarkmode.toggle();</pre><p>Demonstração: feche os slides e alterne o tema. Modo escuro é uma preferência visual, não uma garantia de acessibilidade.</p>'],
 ['02 · Alertify.js', '<p><strong>Para que serve:</strong> criar alertas e diálogos com mensagens claras.</p><p><strong>Como usamos:</strong> cada resposta do quiz abre um diálogo explicativo. O mesmo texto fica na página em uma região com role="status".</p><pre>alertify.alert(\n  "Resposta correta!",\n  "O voto em branco não vai para candidatos."\n);</pre><p>Demonstração: responda uma pergunta e observe o feedback. O significado não depende apenas da cor.</p>'],
 ['03 · RecordRTC', '<p><strong>Para que serve:</strong> gravar áudio ou vídeo no navegador. Neste projeto usamos áudio.</p><pre>const stream = await navigator.mediaDevices\n  .getUserMedia({ audio: true });\nconst recorder = RecordRTC(stream, { type: "audio" });\nrecorder.startRecording();\nrecorder.stopRecording(() =&gt; {\n  const blob = recorder.getBlob();\n});</pre><p>A API nativa solicita o microfone. A biblioteca faz a gravação. O Blob permite ouvir e baixar o arquivo, sem envio a servidor.</p>'],
 ['Demonstração e avaliação', '<ol><li>Alterne o tema e navegue com Tab e Enter.</li><li>Responda o quiz e leia os diálogos.</li><li>Autorize o microfone, grave, pare, ouça e baixe.</li></ol><p><strong>O que as bibliotecas simplificaram:</strong> transformação visual, gestão de diálogos e captura de mídia, sem escrever esses mecanismos do zero.</p><p><strong>Limites:</strong> o microfone exige permissão e ambiente seguro. Teclado, rótulos e contraste continuam sendo responsabilidade de quem desenvolve.</p>'],
 ['Fontes e conclusão', '<p><strong>Conteúdo:</strong> Glossário Eleitoral e esclarecimentos do Tribunal Superior Eleitoral, vinculados na página.</p><p><strong>Documentação:</strong> darkmodejs.learn.uno · alertifyjs.com · recordrtc.org.</p><p>Três bibliotecas, três funções: conforto visual, feedback e expressão por voz.</p><p>O código completo, com comentários, está disponível no botão “Baixar código”.</p>']
];
let slideIndex = 0;
function renderSlide() { $('slide-body').innerHTML = `<h2 id="slide-title">${slides[slideIndex][0]}</h2>${slides[slideIndex][1]}`; $('slide-count').textContent = `${slideIndex + 1} / ${slides.length}`; $('prev-slide').disabled = slideIndex === 0; $('next-slide').disabled = slideIndex === slides.length - 1; $('slides').scrollTop = 0; }
$('present').addEventListener('click', () => { slideIndex = 0; renderSlide(); $('slides').showModal(); });
$('close-slides').addEventListener('click', () => $('slides').close()); $('prev-slide').addEventListener('click', () => { if (slideIndex > 0) { slideIndex--; renderSlide(); } }); $('next-slide').addEventListener('click', () => { if (slideIndex < slides.length - 1) { slideIndex++; renderSlide(); } });
$('slides').addEventListener('keydown', e => { if (e.key === 'ArrowRight') { e.preventDefault(); $('next-slide').click(); } if (e.key === 'ArrowLeft') { e.preventDefault(); $('prev-slide').click(); } });
// Integração opcional: somente navegação entre slides, sem acesso ao microfone.
if (document.modelContext?.registerTool) { try { Promise.resolve(document.modelContext.registerTool({ name: 'abrir_slide', title: 'Abrir slide da apresentação', description: 'Abre um dos sete slides educativos sobre o projeto.', inputSchema: { type: 'object', properties: { numero: { type: 'integer', minimum: 1, maximum: 7 } }, required: ['numero'], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: input => { if (!Number.isInteger(input.numero) || input.numero < 1 || input.numero > 7) throw new Error('Informe um número de 1 a 7.'); slideIndex = input.numero - 1; renderSlide(); if (!$('slides').open) $('slides').showModal(); return { numero: input.numero, titulo: slides[slideIndex][0] }; } })).catch(() => {}); } catch {} }
